export const resourcesZH = {
    SearchHint: "例如：React课程",
    Home: "家",
    Services: "服务",
    Contact: "联系",
    About: "关于",
    Submit: "提交",
    NewsL: "订阅我们的新闻通讯以保持更新。",
    Main: "主页",
    Privacy: "隐私",
    WebDev: "网页开发",
    MobileDev: "移动应用开发",
    Infra: "基础设施",
    Net: "网络",
    HelpDesk: "帮助台",
    FB: "脸书",
    ING: "Instagram",
    X: "推特",
    IN: "领英",
    WP: "WhatsApp",
    YT: "YouTube",
    Jobs: "工作",
    Partners: "合作伙伴",
    Resources: "资源",
    SocialMedia: "社交媒体",
    More: "更多"
}
