export const resourcesHI = {
    SearchHint: "उदाहरण: React कोर्स",
    Home: "घर",
    Services: "सेवाएँ",
    Contact: "संपर्क",
    About: "के बारे में",
    Submit: "प्रस्तुत करें",
    NewsL: "सूचित रहने के लिए हमारे समाचार पत्र की सदस्यता लें।",
    Main: "मुख्य",
    Privacy: "गोपनीयता",
    WebDev: "वेब विकास",
    MobileDev: "मोबाइल ऐप विकास",
    Infra: "बुनियादी ढांचा",
    Net: "नेटवर्क",
    HelpDesk: "सहायता डेस्क",
    FB: "फेसबुक",
    ING: "इंस्टाग्राम",
    X: "ट्विटर",
    IN: "लिंक्डइन",
    WP: "व्हाट्सएप",
    YT: "यूट्यूब",
    Jobs: "नौकरियां",
    Partners: "साझेदार",
    Resources: "संसाधन",
    SocialMedia: "सोशल मीडिया",
    More: "अधिक"
}
