export const resourcesPT = {
    SearchHint: "por exemplo: curso de React",
    Home: "Casa",
    Services: "Serviços",
    Contact: "Contato",
    About: "Sobre",
    Submit: "Enviar",
    NewsL: "Inscreva-se em nosso boletim informativo para se manter informado.",
    Main: "Principal",
    Privacy: "Privacidade",
    WebDev: "Desenvolvimento Web",
    MobileDev: "Desenvolvimento de Aplicativos Móveis",
    Infra: "Infraestrutura",
    Net: "Redes",
    HelpDesk: "Mesa de Ajuda",
    FB: "Facebook",
    ING: "Instagram",
    X: "Twitter",
    IN: "LinkedIn",
    WP: "WhatsApp",
    YT: "YouTube",
    Jobs: "Empregos",
    Partners: "Parceiros",
    Resources: "Recursos",
    SocialMedia: "Mídias Sociais",
    More: "Mais"
}
