export const resourcesES = {
    SearchHint: "por ejemplo: curso de React",
    Home: "Casa",
    Services: "Servicios",
    Contact: "Contacto",
    About: "Acerca de",
    Submit: "Enviar",
    NewsL: "Suscríbete a nuestro boletín para mantenerte informado.",
    Main: "Principal",
    Privacy: "Privacidad",
    WebDev: "Desarrollo Web",
    MobileDev: "Desarrollo de Aplicaciones Móviles",
    Infra: "Infraestructura",
    Net: "Redes",
    HelpDesk: "Mesa de Ayuda",
    FB: "Facebook",
    ING: "Instagram",
    X: "Twitter",
    IN: "LinkedIn",
    WP: "WhatsApp",
    YT: "YouTube",
    Jobs: "Empleos",
    Partners: "Socios",
    Resources: "Recursos",
    SocialMedia: "Redes Sociales",
    More: "Más"
}
